### ISSUE TITLE
Would you consider a more permissive license?

### ISSUE THREAD

**Issue by tdrhq** [brown/swank-client#3]
This library would be very useful for me. And I know I'm being selfish in asking this, but would you be open to a more permissive license? My end goal is to use it in a commercial application (binary built with LispWorks).

I completely understand if that's not something you want to do though. Just wanted to make sure your choice of GPL was intentional.

**Comment by brown** [comment]
Generally, I would be happy to license any code that I've written in a more permissive way for use in a specific commercial application.  In this case, however, the code was derived from other GPL-licensed code and so must remain under that license.

**Comment by tdrhq** [comment]
@brown Yeah, I figured that after posting this. Thanks anyway!
