### ISSUE TITLE
Prior work

### ISSUE THREAD

**Issue by njordhov** [brown/swank-client#4]
I implemented a swank-client for Common Lisp many years ago as part of the now defunct MCLIDE project. Perhaps parts can be of use:

https://github.com/njordhov/mclide/tree/master/mclide/src/swank-client

You have my permission to take whatever you like from the sources. Attribution is optional. 

A key insight from my development is that the transportation protocol can be shared between the client and server, using the same code on both sides. I successfully lobbied to factor it out into the [rpc module](https://github.com/slime/slime/blob/master/swank/rpc.lisp) in swank.

**Comment by brown** [comment]
Thanks very much.  The Swank protocol code here was derived from GPL code in the Slime distribution a while ago, which is why the license is GPL.  I'll consider substituting the public domain implementation in slime/swank/rpc.lisp.
