### ISSUE TITLE
The value is not of type `SWANK::MULTITHREADED-CONNECTION`

### ISSUE THREAD

**Issue by jcguu95** [brown/swank-client#5]
I'm testing `swank-client` in a minimal setting. To reproduce the error, open two `sbcl` in two separate terminals. In the first repl, enter the following

```
(ql:quickload :swank)
(swank:create-server :port 9000 :dont-close t)
(defvar *y* 7)
(in-package :cl)
(defvar *y* 8)
```

Good. No errors. Now I'm going to connect to this repl using `swank-client` from the second repl. So in the second repl, enter the following

```
(ql:quickload :swank-client)
(in-package :swank-client)
(defvar *c* (slime-connect "localhost" 9000))
(slime-eval '(+ 1 1) *c*)
```

No errors, with the last form returns `2` as expected. Enter the real test: `(slime-eval '*y* *c*)`, and it returns an error

```
debugger invoked on a TYPE-ERROR in thread
#<THREAD "swank dispatcher for localhost/9000" RUNNING {1004448373}>:
  The value
    NIL
  is not of type
    SWANK::MULTITHREADED-CONNECTION

The current thread is not at the foreground,
SB-THREAD:RELEASE-FOREGROUND has to be called in #<SB-THREAD:THREAD "main thread" RUNNING {1001568103}>
for this thread to enter the debugger.
```

The repl then hangs there without returning to the prompt.

**Comment by brown** [comment]
Sorry for the delay in responding.  I just noticed this bug report.

The error message and behavior can definitely be improved.

The root problem is that you are trying to evaluate 'swank-client:*y* remotely and the remote Lisp does not have a swank-client package.

**Comment by jcguu95** [comment]
Thank you @brown.

For those who are interested, a minimal working example is given in the following.

**server**

``` lisp
(ql:quickload :swank)
(swank:create-server :port 9000 :dont-close t)
(defvar *y* 7)
```

**client**

``` lisp
(ql:quickload :swank-client)
(defvar *c* (swank-client:slime-connect "localhost" 9000))
(swank-client:slime-eval '*y* *c*)
```
