### ISSUE TITLE
REPEAT inside LOOP

### ISSUE THREAD

**Issue by Yehouda** [brown/swank-client#7]
change
 https://github.com/brown/swank-client/commit/0b3bd8973c0d92ff1f3030e37b6f34ae8012143b 

moved the REPEAT inside LOOP to the end, but that contradicts the CL standard in 
http://www.lispworks.com/documentation/HyperSpec/Body/06_aba.htm
which states:
"The iteration control clauses _for_, _as_, and _repeat_ must precede any other loop clauses, except _initially_, _with_, and _named_, since they establish variable bindings"

The first paragraph of the desciption of termination test clauses http://www.lispworks.com/documentation/HyperSpec/Body/06_ad.htm also impliess that REPEAT needs to be in the prolog.

This doesn't fit with the syntax of LOOP in:
http://www.lispworks.com/documentation/HyperSpec/Body/m_loop.htm

but it actually makes more sense, because the form of REPEAT is evaluated only once, and if it returns 0 the body of  the LOOP form is not evaluated. 

LispWorks gives an error for the REPEAT in the end. 

Putting the REPEAT after the FOR but before the body match both definitions, so probably the best approach. 

                     (loop for i from 2  repeat +server-count+ collect i)
  
And actually, even better would be: 

                   (loop for i from 2  below (+ 2  +server-count+) collect i)

Because this has only one counter.

**Comment by brown** [comment]
Thanks very much for letting me know.  I will fix the problem.
